import os
import requests
import pandas as pd
import torch
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

# Constants
DATA_DIR = 'data'
DATASET_URL = 'https://deepchemdata.s3-us-west-1.amazonaws.com/datasets/HIV.csv'
DATASET_PATH = os.path.join(DATA_DIR, 'HIV.csv')
TIME_BUDGET = 300  # 5 minutes
FINGERPRINT_SIZE = 2048

def download_dataset():
    if not os.path.exists(DATA_DIR):
        os.makedirs(DATA_DIR)
    if not os.path.exists(DATASET_PATH):
        print(f"Downloading dataset from {DATASET_URL}...")
        response = requests.get(DATASET_URL)
        with open(DATASET_PATH, 'wb') as f:
            f.write(response.content)
        print("Download complete.")

def smiles_to_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return np.array(AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=FINGERPRINT_SIZE))

def prepare_data():
    # Check for cached tensors first (generated by cache_data.py)
    cache_files = [
        os.path.join(DATA_DIR, 'X_train.pt'),
        os.path.join(DATA_DIR, 'y_train.pt'),
        os.path.join(DATA_DIR, 'X_val.pt'),
        os.path.join(DATA_DIR, 'y_val.pt'),
    ]
    if all(os.path.exists(f) for f in cache_files):
        print("Loading cached tensors...")
        X_train = torch.load(cache_files[0], weights_only=True)
        y_train = torch.load(cache_files[1], weights_only=True)
        X_val = torch.load(cache_files[2], weights_only=True)
        y_val = torch.load(cache_files[3], weights_only=True)
        print(f"Loaded: Train={len(X_train)}, Val={len(X_val)}")
        return X_train, y_train, X_val, y_val

    # Fallback: featurize from scratch
    print("No cached tensors found. Run cache_data.py first for faster startup.")
    download_dataset()
    df = pd.read_csv(DATASET_PATH)

    fps = []
    labels = []
    skipped = 0

    for _, row in df.iterrows():
        fp = smiles_to_fp(row['smiles'])
        if fp is not None:
            fps.append(fp)
            labels.append(row['HIV_active'])
        else:
            skipped += 1

    print(f"Processed {len(fps)} molecules, skipped {skipped} invalid SMILES")

    X = np.array(fps)
    y = np.array(labels)

    n_active = y.sum()
    n_inactive = len(y) - n_active
    print(f"Class balance: {int(n_active)} active ({100*n_active/len(y):.1f}%), {int(n_inactive)} inactive ({100*n_inactive/len(y):.1f}%)")

    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    return (torch.tensor(X_train, dtype=torch.float32),
            torch.tensor(y_train, dtype=torch.float32),
            torch.tensor(X_val, dtype=torch.float32),
            torch.tensor(y_val, dtype=torch.float32))

def evaluate_metric(model, X_val, y_val):
    model.eval()
    with torch.no_grad():
        outputs = model(X_val).squeeze()
        probs = torch.sigmoid(outputs).cpu().numpy()
        try:
            auc = roc_auc_score(y_val.cpu().numpy(), probs)
        except ValueError:
            auc = 0.5
    return auc

if __name__ == '__main__':
    X_train, y_train, X_val, y_val = prepare_data()
    print(f"Data prepared. Train size: {len(X_train)}, Val size: {len(X_val)}")
    print(f"Fingerprint size: {FINGERPRINT_SIZE}")
